vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO altseed/LLGI
    REF d5291af13cb18fcf9a63f8fe8d65b5979de1f332
    SHA512 561ba2f06813a4204b13d59034c1f18384af1639a78856ece7cacb16ca79896663b3d59215ffb11d5860ae8f2ef8b694dfdf2716078061c937aacdfc42ec04ac
    HEAD_REF master
)

vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
        vulkan  BUILD_VULKAN
        vulkan  BUILD_VULKAN_COMPILER
)

get_filename_component(HEADER_DIR ${CURRENT_INSTALLED_DIR}/include ABSOLUTE)

vcpkg_cmake_configure(
    SOURCE_PATH ${SOURCE_PATH}
    OPTIONS
        ${FEATURE_OPTIONS}
        -DUSE_THIRDPARTY_DIRECTORY=OFF
        -DGLSLANG_INCLUDE_DIR=${HEADER_DIR}
        -DGLSLANG_WITHOUT_INSTALL=ON
        -DSPIRVCROSS_INCLUDE_DIR=${HEADER_DIR}
        -DSPIRVCROSS_WITHOUT_INSTALL=ON
        -DUSE_CREATE_COMPILER_FUNCTION=OFF
)
vcpkg_cmake_install()
vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake)

file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/llgi RENAME copyright)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)